api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', Home.as_view(), name = 'index'),
    path('category/<str:slug>/', PostsByCategory.as_view(), name='category'),
    path('tag/<str:slug>/', PostsByTag.as_view(), name='tag'),
    path('post/<str:slug>/', GetPost.as_view(), name='post'),
    path('search/', Search.as_view(), name='search'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.authtoken.views import obtain_auth_token

from orders.views import stripe_webhook_view
from products.views import *
 

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('dop/', include('dop.urls')),
    path('blog/', include('blog.urls')), 
    path('orders/', include('orders.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('api/', include('api.urls')),
    path('api-token-auth/', obtain_auth_token),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    ]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from audioop import reverse
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, verbose_name='Url', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={"slug": self.slug})

    class Meta:
        ordering = ['title']
        verbose_name = 'PostCategory'
        verbose_name_plural = 'PostCategoties'



class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, verbose_name='Url', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tag', kwargs={"slug": self.slug})

    class Meta:
        ordering = ['title']
        verbose_name = 'PostTag'
        verbose_name_plural = 'PostTags'





class Post(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, verbose_name='Url', unique=True)
    author = models.CharField(max_length=100)
    content = models.TextField(blank = True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name= 'Published')
    photo = models.ImageField(upload_to = 'post_image/%Y-%m-%d', blank = True)
    views = models.IntegerField(default = 0, verbose_name='Numbers of views')
    category = models.ForeignKey(Category, on_delete= models.PROTECT, related_name= 'posts')
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={"slug": self.slug})  # {{ post.get_absolute_url }}

    class Meta:
        ordering = ['-created_at']

blog/views.py
from django.shortcuts import render
from django.http import HttpRequest
from django.views.generic import ListView, DetailView
from django.db.models import F
from .models import *
# Create your views here.


class Home(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwarg):
        context = super().get_context_data(**kwarg)
        context['title'] = 'i Creame Blog '
        return context


class PostsByCategory(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['title'] = Category.objects.get(slug=self.kwargs['slug'])
        return context


class PostsByTag(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        context['title'] = 'Tags : ' + str(Tag.objects.get(slug=self.kwargs['slug']))
        return context


class GetPost(DetailView):
    model = Post
    template_name = 'blog/single.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Post.objects.get(slug=self.kwargs['slug'])
        self.object.views = F('views') + 1
        self.object.save()
        self.object.refresh_from_db()
        return context


class Search(ListView):
    template_name = 'blog/search.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        return Post.objects.filter(title__icontains=self.request.GET.get('s'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'iCreame Search'
        context['s'] = f"s={self.request.GET.get('s')}&"
        return context




from django import template
from blog.models import Post, Tag

register = template.Library()


@register.inclusion_tag('blog/popular_posts_tpl.html')
def get_popular(cnt=3):
    posts = Post.objects.order_by('-views')[:cnt]
    return {"posts": posts}


@register.inclusion_tag('blog/tags_tpl.html')
def get_tags():
    tags = Tag.objects.all()
    return {"tags": tags}

blog/templates/blog/index.html
{% extends 'users/base.html' %}
{% load static %}



{% block content %}



    <!-- Header Start -->
<div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
    <div class="container text-center py-5">
        <h1 class="text-white display-3 mt-lg-5">Blog</h1>
        <div class="d-inline-flex align-items-center text-white">
            <div class="row">
            <p class="m-0"><a class="text-primary" href="{% url 'blog:index' %}">All</a></p>
            </div>
           
        </div>

        
        <div class="row">  

        </div>
    </div>
</div>
    <!-- Header End -->




    <!-- Services Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="section-title position-relative mb-5">Interesting Facts About Ice Creame</h1>
                </div>
                <div class="col-lg-6 mb-5 mb-lg-0 pb-5 pb-lg-0"></div>
            </div>
            <div class="row">
                
                    

                        {% for post in posts %}
                        <div class="col-12">
                        <div class="service-item">
                            <div class="service-img mx-auto">
                                {% if post.photo %}
                                <img class="rounded-circle w-100 h-100 bg-light p-3" src="{{ post.photo.url }}"  style="object-fit: cover;">
                                {% else %}
                                <img class="rounded-circle w-100 h-100 bg-light p-3" src="{% static 'img/service-1.jpg' %}" style="object-fit: cover;">
                                {% endif %}
                            </div>
                            <div class="position-relative text-center bg-light rounded p-4 pb-5" style="margin-top: -75px;">
                                <h5 class="font-weight-semi-bold mt-5 mb-3 pt-5">{{ post.title }}</h5>
                                <p>{{ post.content|truncatewords_html:50|safe }}</p>
                                <a href="{% url 'blog:post' post.slug %}" class="border-bottom border-secondary text-decoration-none text-secondary">Learn More</a>
                            </div>
                        </div>
                        </div>
                        {% endfor %}

                    
                
            </div>
        </div>
    </div>
    <!-- Blog End -->
               
    <!-- Paginations -->
<div class="col-12 text-center">
{% if page_obj.has_other_pages %}
<div class="pegination">
    <div class="nav-links">

        {% for p in page_obj.paginator.page_range %}
            {% if page_obj.number == p %}
            <span class="page-numbers current">{{ p }}</span>
            {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
            <a class="page-numbers" href="?page={{ p }}">{{ p }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class="page-numbers" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
        {% endif %}
    </div>
</div>
{% endif %}
</div>





<div class="newsletter">
    <h2 class="sidebar-title">Search</h2>
    <form action="{% url 'blog:search' %}" method="get">
        <input type="text" name="s" placeholder="Search in titles...">
        <input type="submit" value="Search">
    </form>
</div>

{% endblock %}

blog/templates/blog/search.html
{% extends 'users/base.html' %}
{% load static %}


{% block content %}

<section class="row justify-content-center">
    
    <div class="container">

        <div class="row justify-content-center">

        <div class="border-top" style="border-top: 1px solid #40c4ff;"></div>
        <div class="row ">
           

                {% for post in posts %}
                <div class="col-lg-4 py-5">
                    <div class="single-post">

                        {% if post.photo %}
                        <img class="rounded-circle w-100 h-100 bg-light p-3" src="{{ post.photo.url }}"  style="object-fit: cover;">
                        {% else %}
                        <img class="rounded-circle w-100 h-100 bg-light p-3" src="{% static 'img/service-1.jpg' %}" style="object-fit: cover;">
                        {% endif %}

                        <h3><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a></h3>
                     
                        {{ post.content|truncatewords_html:20|safe }}
                        <i class="fa fa-circle px-3"></i>
                    </div>
                </div>
                {% empty %}
                <p>Nothing...</p>
                {% endfor %}
            
        </div>
        </div>
    </div>
    

    {% if page_obj.has_other_pages %}
    <div class="pegination">
        <div class="nav-links">

            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                <span class="page-numbers current">{{ p }}</span>
                {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                <a class="page-numbers" href="?{{ s }}page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a class="page-numbers" href="?{{ s }}page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            {% endif %}
        </div>
    </div>
    {% endif %}

</section>
{% endblock %}

blog/templates/blog/single.html
{% extends 'users/base.html' %}
{% load static %}


{% block content %}



<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <h1 class="section-title position-relative text-center mb-5">{{ post.title }}</h1>
            </div>
        </div>                         
               <div class="single-content">
                    <div>
                        <span>Category: <a href="{% url 'blog:category' post.category.slug %}">{{ post.category }}</a></span>
                        <br>
                        {% if post.tags.exists %}
                        <span>
                            Tags:
                            {% for tag in post.tags.all %}
                            <a href="{% url 'blog:tag' tag.slug %}">{{ tag.title }}</a>
                            {% endfor %}
                        </span>
                        <br>
                        {% endif %}
                        <span>Views: {{ post.views }}</span>
                    </div>
                                    
                </div>
        <div class="row">
            <div class="col-lg-4" style="min-height: 400px;">
                <div class="position-relative h-100 rounded overflow-hidden">
                    {% if post.photo %}
                    <img class="rounded-circle w-100 h-100 bg-light p-3" src="{{ post.photo.url }}"  style="object-fit: cover;">
                    {% else %}
                    <img class="rounded-circle w-100 h-100 bg-light p-3" src="{% static 'img/service-1.jpg' %}" style="object-fit: cover;">
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4 py-5">
                                
                <span>Views: {{ post.views }}</span>
                <p> {{ post.content|safe }}</p>
                
            </div>
        </div>
    </div>
</div>


<section class="single-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="border-top">
                    <div class="col-md-8">
                        <div class="blog-area">
                            <div class="blog-area-part">


                            </div>


                        </div>
                    </div>
                    <div class="col-md-4">

                        <div class="newsletter">
                            <h2 class="sidebar-title">Search</h2>
                            <form action="{% url 'blog:search' %}" method="get">
                                <input type="text" name="s" placeholder="Search in titles...">
                                <input type="submit" value="Search">
                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/spam.html
<section class="single-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="border-top">
                    <div class="col-md-8">
                        <div class="blog-area">
                            <div class="blog-area-part">
                            <div class="service-img mx-auto">
                                {% if post.photo %}
                                <img class="rounded-circle w-100 h-100 bg-light p-3" src="{{ post.photo.url }}"  style="object-fit: cover;">
                                {% else %}
                                <img class="rounded-circle w-100 h-100 bg-light p-3" src="{% static 'img/service-1.jpg' %}" style="object-fit: cover;">
                                {% endif %}
                            </div>
                                <h2>{{ post.title }}</h2>
                                <div class="single-content">
                                    <div>
                                        <span>Category: <a href="{{ post.category.slug}}">{{ post.category }}</a></span>
                                        <br>
                                        {% if post.tags.exists %}
                                        <span>
                                            Tags:
                                            {% for tag in post.tags.all %}
                                            <a href="{{ tag.slug }}">{{ tag.title }}</a>
                                            {% endfor %}
                                        </span>
                                        <br>
                                        {% endif %}
                                        <span>Views: {{ post.views }}</span>
                                    </div>
                                    {{ post.content|safe }}
                                </div>
                            </div>


                        </div>
                    </div>
                    <div class="col-md-4">

                        <div class="newsletter">
                            <h2 class="sidebar-title">Search</h2>
                            <form action="{% url 'blog:search' %}" method="get">
                                <input type="text" name="s" placeholder="Search...">
                                <input type="submit" value="Search">
                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- from single html  working part-->
<div>
    <span>Category: <a href="{% url 'blog:category' post.category.slug %}">{{ post.category }}</a></span>
    <br>
    {% if post.tags.exists %}
    <span>
        Tags:
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:tag' tag.slug %}">{{ tag.title }}</a>
        {% endfor %}
    </span>
    <br>
    {% endif %}
    <span>Views: {{ post.views }}</span>
</div>




<!-- headers from index html   need  -->
    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
        <div class="container text-center py-5">
            <h1 class="text-white display-3 mt-lg-5">Blog</h1>
            <div class="d-inline-flex align-items-center text-white">
                <div class="row">
                <p class="m-0"><a class="text-primary" href="{% url 'blog:index' %}">All</a></p>
                {% for post in object_list %}
                    <i class="fa fa-circle px-3"></i>
                    <p class="m-0">
                    <a class="text-white" href="{% url 'blog:category' post.category.slug %}">{{ post.categry.title}}</a>
                    </p>
                {% endfor %}
                </div>
    
                
            </div>
    
            
            <div class="row">  
                <div class="d-inline-flex align-items-center text-white">
                    {% for tag in posts.tags.all %}
                    <h5 class="sidebar-title">Tags:  </h5>
                    {% endfor %}            
                    <a href="{% url 'blog:tag' tag.slug %}">{{ tag.slug }} - </a>
                </div>
            </div>
        </div>
    </div>
        <!-- Header End -->





<!-- for popular post and Tags and Categories -->

<h2 class="sidebar-title">Popular posts</h2>
<div class="grid">
    {% for post in posts %}
    <div class="portfolio-item popular">

        <div class="portfolio-text">
            <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
        </div>
    </div>
    {% endfor %}
</div>

<div class="tags">
    <h2 class="sidebar-title">Tags</h2>
    {% for tag in tags %}
    <p><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></p>
    {% endfor %}
</div>


<div class="{{ menu_class }}">
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        {% for item in categories %}
        <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
        {% endfor %}
    </ul>
</div>
<!-- in views.py or create templatestags(also create __init__.py)

from django import template
from blog.models import *

register = template.Library()


@register.inclusion_tag('blog/popular_posts_tpl.html')
def get_popular(cnt=3):
    posts = Post.objects.order_by('-views')[:cnt]
    return {"posts": posts}


@register.inclusion_tag('blog/tags_tpl.html')
def get_tags():
    tags = Tag.objects.all()
    return {"tags": tags} 

@register.inclusion_tag('blog/menu_tpl.html')
def show_categories(menu_class='menu'):
    categories = Category.objects.all()
    return {"categories": categories, "menu_class": menu_class}
 -->

blog/templates/blog/tags_tpl.html

    <h2 class="sidebar-title">Tags</h2>
    {% for tag in tags %}
    <p><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></p>
    {% endfor %}